<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="classroom">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="code" type="xs:string"/>
                            <xs:element name="inventory_number">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="1"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                            </xs:element>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="price">
                                <xs:simpleType>
                                    <xs:restriction base="xs:double">
                                        <xs:minInclusive value="0.0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="category" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Computer"/>
                                    <xs:enumeration value="Projector"/>
                                    <xs:enumeration value="Furniture"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>